//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudController.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string SimGuid { get; set; }
        public string ModelName { get; set; }
        public string LanguageName { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
